### ISSUE TITLE
capstone I - wireframes

### ISSUE THREAD

**Issue by mdewey** [WillWarren1/assignments#19]
# It starts with a plan.

We are starting the final stretch of the cohort. This means we are starting to focus on our final projects.

When we go to start a new project. The first step is to create an elevator pitch. This is a short description that describes what your final project is doing. This should be similar to what you said during pitches.

The second step is to always plan out what we are doing. These early plans often take the shape of wireframes. This means that our first task for the capstone is to create our wireframes.

The elevator pitch and wire frames should be treated as a detailed road map. When these are created, these should be treated as law; it can be changed but must be changed with purpose.

## Objectives

- Finalize the idea for your capstone
- Create wireframes for your capstone project
- Using `app-app to start implementing your HTML

## Requirements

- Using your favorite way to create wireframes (paper, whiteboard, website), create all the pages for your site no matter how simple the pages are.
- Create a new repository for your capstone project

### Explorer Mode

- [ ] Create the elevator pitch for your final projects.
- [ ] Place this in the `README.md` of your capstone project repository

- [ ] Create a wireframe for each page in your page you capstone.
- [ ] Place these wireframes in a `.idea` folder of your capstone project repository.

## Additional Resources

- [Adobe XD](https://www.adobe.com/products/xd.html), _free_ software from Adobe for designing and prototyping website and mobile apps.
- [Moqups](https://moqups.com/), a web-based tool for collaborating on wireframes, mockups, and prototypes.

**Comment by WillWarren1** [comment]
https://github.com/WillWarren1/arrrrg not sure why the images are appearing in my repository as separate files and not in the idea folder i created, but heres my wireframe. I wanted to spend more time on it today and actually delve into html and some css but i was getting over this sickness all day today.

**Comment by mdewey** [comment]
I like the theming and layout so far. I would like to see 2 things: 

1) more details on the game
2) a mobile version as well, just so you know what that would like like

**Comment by mdewey** [comment]
Your homework was marked: **Acceptable**

![Hmm ok ](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a5311edd7d489ed156ec6b740b1cfac394c2c264/unicorn%20pug.gif)
> &ldquo;Hmm ok &rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/18)**__
