### ISSUE TITLE
Week 06 - Day 3 - Choose your own API Adventure

### ISSUE THREAD

**Issue by mdewey** [WillWarren1/assignments#21]
# Choose your own API Adventure

In this assignment, you'll build a front end for an API of your choice

## Objectives

- Reinforce component architecture in React
- Reinforce reading of API documentation (some are great, and some are terrible)
- Creating and designing your own features for a web app

## Requirements

We're going to build a front end for an API of your choice. Choose one from [this list](https://github.com/toddmotto/public-apis)

_NOTE_ You'll need to choose one with `Auth` being `No` or `apiKey` since we haven't covered `OAuth` authentication yet.

_NOTE_ You'll also need to check to see if the API will work from your browser. You can do a quick check by making a small `create-react-app`, doing an `axios.get` or `fetch` of one API URL and see if you get browser errors.

### Explorer Mode

- [x] Read your API docs
- [x] Use Postman to make some API requests to be familiar with the API and the data it returns
- [x] Create a list of the features you are going to create and how they will work
- [x] Design your User Interface
- [x] create-react-app
- [x] Design your HTML statically in `App.js`
- [ ] Make it dynamic
- [ ] Use components when needed
- [ ] Deploy it and share it with friends

**Comment by WillWarren1** [comment]
https://github.com/WillWarren1/choose-api here's what i have for choose your own api right now. I'd pursue it further but im behind and would like to focus on capstone. it is not currently responsive and styling is extremely simplistic and some image sizes from the API seem to display wonkily, but the API call works so small victories.

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa7a355c1c44cd588feef47afca922431993c337/giphy-9.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/74)**__
