### ISSUE TITLE
Week 06 - Day 4 - Capstone HTML

### ISSUE THREAD

**Issue by mdewey** [WillWarren1/assignments#22]
# Let's get visual!

With the wireframes created, we need to start breathing life into our application. The next step would be to create HTML & CSS. This is the next step because, remember, it all comes down to HTML. This is what the user sees

_NOTE_: Really take advantage of this weekend to get make progress on your capstone. Like the last 6 weeks, the next 6 weeks will go by _fast_.

## Objectives

- Create HTML and based off of your wireframes
## Requirements

- Using `app-app` to start implementing your wireframes using HTML and CSS.

### Explorer Mode

- [ ] Create the HTML and CSS version of your wireframes. Stay as true as possible. This should focus on static HTML and CSS.
- [ ] No matter how far you get, submit what you have on Sunday night.

_NOTE_ : Always go static content (HTML and CSS) before making your app dynamic (adding React)

_NOTE_: Do not feel pressured to make components yet, giant render functions are okay _for now_

_NOTE_: FInalize your wireframes before you start coding. It will make your life easier.

**Comment by WillWarren1** [comment]
![pirateARG-01](https://user-images.githubusercontent.com/46932848/54500703-f8363400-48f5-11e9-9b3e-b26598d6b9d7.png)
i am currently working on css, but in case i forget to submit tonight, I'm attaching the image of what the home page will look like once i slice up this image and pull it into an images folder for the project. HTML and pages work fine so far I just have to attach parts of this picture and some others (that will mostly reuse layers from this). I'm still a little behind but catching up as quickly as I can. I will be drafting up ERDs as well this weekend

**Comment by WillWarren1** [comment]
https://github.com/WillWarren1/arrrrg

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--395b5be9a8246c8cf018274388a5d5392825ae8e/giphy-2.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/67)**__
